/*
 *  R : A Computer Language for Statistical Data Analysis
 *  Copyright (C) 1995, 1996  Robert Gentleman and Ross Ihaka
 *  Copyright (C) 1997--2016  The R Core Team
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, a copy is available at
 *  https://www.R-project.org/Licenses/
 */

/* Names of  .Internal(.) and .Primitive(.)  R functions
 *
 * Must all return SEXP because of CCODE in Defn.h.
 * do_math*() and do_cmathfuns are in ../main/arithmetic.h
 */

#ifndef R_INTERNAL_H
#define R_INTERNAL_H


/* Function Names */

#if Win32
SEXP do_mkjunction(SEXP, SEXP, SEXP, SEXP);
SEXP do_shellexec(SEXP, SEXP, SEXP, SEXP);
SEXP do_syswhich(SEXP, SEXP, SEXP, SEXP);
SEXP do_tzone_name(SEXP, SEXP, SEXP, SEXP);
#else
SEXP do_X11(SEXP, SEXP, SEXP, SEXP);
#endif

SEXP do_abs(SEXP, SEXP, SEXP, SEXP);
SEXP do_addCondHands(SEXP, SEXP, SEXP, SEXP);
SEXP do_addTryHandlers(SEXP, SEXP, SEXP, SEXP);
SEXP do_adist(SEXP, SEXP, SEXP, SEXP);
SEXP do_agrep(SEXP, SEXP, SEXP, SEXP);
SEXP do_allnames(SEXP, SEXP, SEXP, SEXP);
SEXP do_anyNA(SEXP, SEXP, SEXP, SEXP);
SEXP do_aregexec(SEXP, SEXP, SEXP, SEXP);
SEXP do_args(SEXP, SEXP, SEXP, SEXP);
SEXP do_arith(SEXP, SEXP, SEXP, SEXP);
SEXP do_ascall(SEXP, SEXP, SEXP, SEXP);
SEXP do_as_environment(SEXP, SEXP, SEXP, SEXP);
SEXP do_asatomic(SEXP, SEXP, SEXP, SEXP);
SEXP do_asfunction(SEXP, SEXP, SEXP, SEXP);
SEXP do_asmatrixdf(SEXP, SEXP, SEXP, SEXP);
SEXP do_asvector(SEXP, SEXP, SEXP, SEXP);
SEXP do_asCharacterFactor(SEXP, SEXP, SEXP, SEXP);
SEXP do_AT(SEXP call, SEXP op, SEXP args, SEXP env);
SEXP do_attach(SEXP,SEXP,SEXP,SEXP);
SEXP do_attr(SEXP, SEXP, SEXP, SEXP);
SEXP do_attrgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_attributes(SEXP, SEXP, SEXP, SEXP);
SEXP do_attributesgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_backsolve(SEXP, SEXP, SEXP, SEXP);
SEXP do_begin(SEXP, SEXP, SEXP, SEXP);
SEXP do_bincode(SEXP, SEXP, SEXP, SEXP);
SEXP do_bind(SEXP, SEXP, SEXP, SEXP);
SEXP do_bindtextdomain(SEXP, SEXP, SEXP, SEXP);
SEXP do_bitwise(SEXP, SEXP, SEXP, SEXP);
SEXP NORET do_break(SEXP, SEXP, SEXP, SEXP);
SEXP do_browser(SEXP, SEXP, SEXP, SEXP);
SEXP do_c(SEXP, SEXP, SEXP, SEXP);
SEXP do_c_dflt(SEXP, SEXP, SEXP, SEXP);
SEXP do_call(SEXP, SEXP, SEXP, SEXP);
SEXP do_cat(SEXP, SEXP, SEXP, SEXP);
SEXP do_chartr(SEXP, SEXP, SEXP, SEXP);
SEXP do_class(SEXP, SEXP, SEXP, SEXP);
SEXP do_classgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_colon(SEXP, SEXP, SEXP, SEXP);
SEXP do_colsum(SEXP, SEXP, SEXP, SEXP);
SEXP do_commentgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_contourLines(SEXP, SEXP, SEXP, SEXP);
SEXP do_cum(SEXP, SEXP, SEXP, SEXP);
SEXP do_curlDownload(SEXP, SEXP, SEXP, SEXP);
SEXP do_curlGetHeaders(SEXP, SEXP, SEXP, SEXP);
SEXP do_curlVersion(SEXP, SEXP, SEXP, SEXP);
SEXP do_debug(SEXP, SEXP, SEXP, SEXP);
SEXP do_delayed(SEXP, SEXP, SEXP, SEXP);
SEXP do_deparse(SEXP, SEXP, SEXP, SEXP);
SEXP do_dim(SEXP, SEXP, SEXP, SEXP);
SEXP do_dimgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_dimnames(SEXP, SEXP, SEXP, SEXP);
SEXP do_dimnamesgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_docall(SEXP, SEXP, SEXP, SEXP);
SEXP do_dotcall(SEXP, SEXP, SEXP, SEXP);
SEXP do_dotcallgr(SEXP, SEXP, SEXP, SEXP);
SEXP do_dotCode(SEXP, SEXP, SEXP, SEXP);
SEXP do_dump(SEXP, SEXP, SEXP, SEXP);
SEXP do_duplicated(SEXP, SEXP, SEXP, SEXP);
SEXP do_dynload(SEXP, SEXP, SEXP, SEXP);
SEXP do_dynunload(SEXP, SEXP, SEXP, SEXP);
SEXP do_eapply(SEXP, SEXP, SEXP, SEXP);
SEXP do_edit(SEXP, SEXP, SEXP, SEXP);
SEXP do_enc2(SEXP, SEXP, SEXP, SEXP);
SEXP do_envirgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_External(SEXP, SEXP, SEXP, SEXP);
SEXP do_Externalgr(SEXP, SEXP, SEXP, SEXP);
SEXP do_eval(SEXP, SEXP, SEXP, SEXP);
SEXP do_expression(SEXP, SEXP, SEXP, SEXP);
SEXP do_filecopy(SEXP, SEXP, SEXP, SEXP);
SEXP do_filepath(SEXP, SEXP, SEXP, SEXP);
SEXP do_fileshow(SEXP, SEXP, SEXP, SEXP);
SEXP do_findinterval(SEXP, SEXP, SEXP, SEXP);
SEXP do_first_min(SEXP, SEXP, SEXP, SEXP);
SEXP do_for(SEXP, SEXP, SEXP, SEXP);
SEXP do_forceAndCall(SEXP, SEXP, SEXP, SEXP);
SEXP do_format(SEXP, SEXP, SEXP, SEXP);
SEXP do_formatC(SEXP, SEXP, SEXP, SEXP);
SEXP do_function(SEXP, SEXP, SEXP, SEXP);
SEXP do_gctime(SEXP, SEXP, SEXP, SEXP);
SEXP do_get(SEXP, SEXP, SEXP, SEXP);
SEXP do_getGraphicsEvent(SEXP, SEXP, SEXP, SEXP);
SEXP do_getGraphicsEventEnv(SEXP, SEXP, SEXP, SEXP);
SEXP do_gettext(SEXP, SEXP, SEXP, SEXP);
SEXP do_grep(SEXP, SEXP, SEXP, SEXP);
SEXP do_grepraw(SEXP, SEXP, SEXP, SEXP);
SEXP do_gsub(SEXP, SEXP, SEXP, SEXP);
SEXP do_iconv(SEXP, SEXP, SEXP, SEXP);
SEXP do_ICUset(SEXP, SEXP, SEXP, SEXP);
SEXP do_identical(SEXP, SEXP, SEXP, SEXP);
SEXP do_if(SEXP, SEXP, SEXP, SEXP);
SEXP do_inspect(SEXP, SEXP, SEXP, SEXP);
SEXP do_internal(SEXP, SEXP, SEXP, SEXP);
SEXP do_interruptsSuspended(SEXP, SEXP, SEXP, SEXP);
SEXP do_invisible(SEXP, SEXP, SEXP, SEXP);
SEXP do_is(SEXP, SEXP, SEXP, SEXP);
SEXP do_isfinite(SEXP, SEXP, SEXP, SEXP);
SEXP do_isinfinite(SEXP, SEXP, SEXP, SEXP);
SEXP do_isloaded(SEXP, SEXP, SEXP, SEXP);
SEXP do_isna(SEXP, SEXP, SEXP, SEXP);
SEXP do_isnan(SEXP, SEXP, SEXP, SEXP);
SEXP do_isunsorted(SEXP, SEXP, SEXP, SEXP);
SEXP do_isvector(SEXP, SEXP, SEXP, SEXP);
SEXP do_lapack(SEXP, SEXP, SEXP, SEXP);
SEXP do_lapply(SEXP, SEXP, SEXP, SEXP);
SEXP do_lazyLoadDBfetch(SEXP, SEXP, SEXP, SEXP);
SEXP do_lazyLoadDBinsertValue(SEXP call, SEXP op, SEXP args, SEXP env);
SEXP do_length(SEXP, SEXP, SEXP, SEXP);
SEXP do_lengthgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_lengths(SEXP, SEXP, SEXP, SEXP);
SEXP do_levelsgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_listdirs(SEXP, SEXP, SEXP, SEXP);
SEXP do_listfiles(SEXP, SEXP, SEXP, SEXP);
SEXP do_log(SEXP, SEXP, SEXP, SEXP);
SEXP do_log1arg(SEXP, SEXP, SEXP, SEXP);
SEXP do_logic(SEXP, SEXP, SEXP, SEXP);
SEXP do_logic2(SEXP, SEXP, SEXP, SEXP);
SEXP do_logic3(SEXP, SEXP, SEXP, SEXP);
SEXP do_machine(SEXP, SEXP, SEXP, SEXP);
SEXP do_makelazy(SEXP, SEXP, SEXP, SEXP);
SEXP do_makelist(SEXP, SEXP, SEXP, SEXP);
SEXP do_mapply(SEXP, SEXP, SEXP, SEXP);
SEXP do_match(SEXP, SEXP, SEXP, SEXP);
SEXP do_matchcall(SEXP, SEXP, SEXP, SEXP);
SEXP do_matprod(SEXP, SEXP, SEXP, SEXP);
SEXP do_Math2(SEXP, SEXP, SEXP, SEXP);
SEXP do_matrix(SEXP, SEXP, SEXP, SEXP);
SEXP do_mget(SEXP, SEXP, SEXP, SEXP);
SEXP do_missing(SEXP, SEXP, SEXP, SEXP);
SEXP do_names(SEXP, SEXP, SEXP, SEXP);
SEXP do_namesgets(SEXP, SEXP, SEXP, SEXP);
SEXP do_nargs(SEXP, SEXP, SEXP, SEXP);
SEXP do_nchar(SEXP,SEXP,SEXP,SEXP);
SEXP do_newenv(SEXP,SEXP,SEXP,SEXP);
SEXP do_nextmethod(SEXP,SEXP,SEXP,SEXP);
SEXP do_ngettext(SEXP, SEXP, SEXP, SEXP);
SEXP do_normalizepath(SEXP, SEXP, SEXP, SEXP);
SEXP do_nzchar(SEXP,SEXP,SEXP,SEXP);
SEXP do_onexit(SEXP, SEXP, SEXP, SEXP);
SEXP do_options(SEXP, SEXP, SEXP, SEXP);
SEXP do_order(SEXP, SEXP, SEXP, SEXP);
SEXP do_parse(SEXP, SEXP, SEXP, SEXP);
SEXP do_paste(SEXP, SEXP, SEXP, SEXP);
SEXP do_pmin(SEXP, SEXP, SEXP, SEXP);
SEXP do_pos2env(SEXP, SEXP, SEXP, SEXP);
SEXP do_pretty(SEXP, SEXP, SEXP, SEXP);
SEXP do_primitive(SEXP, SEXP, SEXP, SEXP);
SEXP do_printdefault(SEXP, SEXP, SEXP, SEXP);
SEXP do_printfunction(SEXP, SEXP, SEXP, SEXP);
SEXP do_prmatrix(SEXP, SEXP, SEXP, SEXP);
SEXP do_psort(SEXP, SEXP, SEXP, SEXP);
SEXP do_quit(SEXP, SEXP, SEXP, SEXP);
SEXP do_quote(SEXP, SEXP, SEXP, SEXP);
SEXP do_random1(SEXP, SEXP, SEXP, SEXP);
SEXP do_random2(SEXP, SEXP, SEXP, SEXP);
SEXP do_random3(SEXP, SEXP, SEXP, SEXP);
SEXP do_range(SEXP, SEXP, SEXP, SEXP);
SEXP do_rank(SEXP, SEXP, SEXP, SEXP);
SEXP do_rapply(SEXP, SEXP, SEXP, SEXP);
SEXP do_readDCF(SEXP, SEXP, SEXP, SEXP);
SEXP do_readEnviron(SEXP, SEXP, SEXP, SEXP);
SEXP do_readLines(SEXP, SEXP, SEXP, SEXP);
SEXP do_recall(SEXP, SEXP, SEXP, SEXP);
SEXP do_refcnt(SEXP, SEXP, SEXP, SEXP);
SEXP do_recordGraphics(SEXP, SEXP, SEXP, SEXP);
SEXP do_regexec(SEXP, SEXP, SEXP, SEXP);
SEXP do_regexpr(SEXP, SEXP, SEXP, SEXP);
SEXP do_relop(SEXP, SEXP, SEXP, SEXP);
SEXP do_relop_dflt(SEXP, SEXP, SEXP, SEXP);
SEXP do_remove(SEXP, SEXP, SEXP, SEXP);
SEXP do_rep(SEXP, SEXP, SEXP, SEXP);
SEXP do_repeat(SEXP, SEXP, SEXP, SEXP);
SEXP NORET do_return(SEXP, SEXP, SEXP, SEXP);
SEXP do_rgb(SEXP, SEXP, SEXP, SEXP);
SEXP do_rowsum(SEXP, SEXP, SEXP, SEXP);
SEXP do_rowscols(SEXP, SEXP, SEXP, SEXP);
SEXP do_S4on(SEXP, SEXP, SEXP, SEXP);
SEXP do_sample(SEXP, SEXP, SEXP, SEXP);
SEXP do_save(SEXP, SEXP, SEXP, SEXP);
SEXP do_saveToConn(SEXP, SEXP, SEXP, SEXP);
SEXP do_saveplot(SEXP, SEXP, SEXP, SEXP);
SEXP do_scan(SEXP, SEXP, SEXP, SEXP);
SEXP do_seq(SEXP, SEXP, SEXP, SEXP);
SEXP do_seq_along(SEXP, SEXP, SEXP, SEXP);
SEXP do_seq_len(SEXP, SEXP, SEXP, SEXP);
SEXP do_serialize(SEXP, SEXP, SEXP, SEXP);
SEXP do_serializeToConn(SEXP, SEXP, SEXP, SEXP);
SEXP do_set(SEXP, SEXP, SEXP, SEXP);
SEXP do_setGraphicsEventEnv(SEXP, SEXP, SEXP, SEXP);
SEXP do_setwd(SEXP, SEXP, SEXP, SEXP);
SEXP do_sprintf(SEXP, SEXP, SEXP, SEXP);
SEXP do_standardGeneric(SEXP, SEXP, SEXP, SEXP);
SEXP do_startsWith(SEXP, SEXP, SEXP, SEXP);
SEXP NORET do_stop(SEXP, SEXP, SEXP, SEXP);
SEXP do_storage_mode(SEXP, SEXP, SEXP, SEXP);
SEXP do_strrep(SEXP, SEXP, SEXP, SEXP);
SEXP do_strsplit(SEXP,SEXP,SEXP,SEXP);
SEXP do_strtoi(SEXP,SEXP,SEXP,SEXP);
SEXP do_sysinfo(SEXP,SEXP,SEXP,SEXP);
SEXP do_syssleep(SEXP,SEXP,SEXP,SEXP);
SEXP do_subassign(SEXP, SEXP, SEXP, SEXP);
SEXP do_subassign_dflt(SEXP, SEXP, SEXP, SEXP);
SEXP do_subassign2(SEXP, SEXP, SEXP, SEXP);
SEXP do_subassign2_dflt(SEXP, SEXP, SEXP, SEXP);
SEXP do_subassign3(SEXP, SEXP, SEXP, SEXP);
SEXP do_subset(SEXP, SEXP, SEXP, SEXP);
SEXP do_subset_dflt(SEXP, SEXP, SEXP, SEXP);
SEXP do_subset2(SEXP, SEXP, SEXP, SEXP);
SEXP do_subset2_dflt(SEXP, SEXP, SEXP, SEXP);
SEXP do_subset3(SEXP, SEXP, SEXP, SEXP);
SEXP do_substitute(SEXP, SEXP, SEXP, SEXP);
SEXP do_summary(SEXP, SEXP, SEXP, SEXP);
SEXP do_switch(SEXP, SEXP, SEXP, SEXP);
SEXP do_sys(SEXP, SEXP, SEXP, SEXP);
SEXP do_sysbrowser(SEXP, SEXP, SEXP, SEXP);
SEXP do_system(SEXP, SEXP, SEXP, SEXP);
SEXP do_tempfile(SEXP, SEXP, SEXP, SEXP);
SEXP do_tilde(SEXP, SEXP, SEXP, SEXP);
SEXP do_tolower(SEXP, SEXP, SEXP, SEXP);
SEXP do_topenv(SEXP, SEXP, SEXP, SEXP);
SEXP do_trace(SEXP, SEXP, SEXP, SEXP);
SEXP do_traceOnOff(SEXP, SEXP, SEXP, SEXP);
SEXP do_trunc(SEXP, SEXP, SEXP, SEXP);
SEXP do_unclass(SEXP, SEXP, SEXP, SEXP);
SEXP do_unlist(SEXP, SEXP, SEXP, SEXP);
SEXP NORET do_usemethod(SEXP, SEXP, SEXP, SEXP);
SEXP do_vapply(SEXP, SEXP, SEXP, SEXP);
SEXP do_warning(SEXP, SEXP, SEXP, SEXP);
SEXP do_while(SEXP, SEXP, SEXP, SEXP);
SEXP do_withVisible(SEXP, SEXP, SEXP, SEXP);
SEXP do_xtfrm(SEXP, SEXP, SEXP, SEXP);

SEXP do_getSnapshot(SEXP, SEXP, SEXP, SEXP);
SEXP do_playSnapshot(SEXP, SEXP, SEXP, SEXP);

SEXP R_do_data_class(SEXP call, SEXP op, SEXP args, SEXP env);
SEXP R_do_set_class(SEXP call, SEXP op, SEXP args, SEXP env);
SEXP R_getS4DataSlot(SEXP obj, SEXPTYPE type);

/* bytecode */
SEXP do_bcclose(SEXP, SEXP, SEXP, SEXP);
SEXP do_is_builtin_internal(SEXP, SEXP, SEXP, SEXP);
SEXP do_disassemble(SEXP, SEXP, SEXP, SEXP);
SEXP do_loadfile(SEXP, SEXP, SEXP, SEXP);
SEXP do_savefile(SEXP, SEXP, SEXP, SEXP);

/* Connections */
SEXP do_readbin(SEXP, SEXP, SEXP, SEXP);
SEXP do_close(SEXP, SEXP, SEXP, SEXP);
SEXP do_url(SEXP, SEXP, SEXP, SEXP);
SEXP do_gzfile(SEXP, SEXP, SEXP, SEXP);
SEXP do_sockconn(SEXP, SEXP, SEXP, SEXP);

SEXP do_lockBnd(SEXP, SEXP, SEXP, SEXP);
SEXP do_regNS(SEXP call, SEXP op, SEXP args, SEXP rho);
SEXP do_unregNS(SEXP call, SEXP op, SEXP args, SEXP rho);
SEXP do_getRegNS(SEXP call, SEXP op, SEXP args, SEXP rho);
SEXP do_importIntoEnv(SEXP call, SEXP op, SEXP args, SEXP rho);

SEXP do_tracemem(SEXP, SEXP, SEXP, SEXP);
SEXP do_retracemem(SEXP, SEXP, SEXP, SEXP);
SEXP do_untracemem(SEXP, SEXP, SEXP, SEXP);

/* .Call implementations of simple do_functions */

SEXP dc_islistfactor(SEXP arg1, SEXP arg2);
SEXP dc_drop(SEXP arg1);
SEXP dc_transpose(SEXP arg1);
SEXP dc_aperm(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_array(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_diag(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_maxcol(SEXP arg1, SEXP arg2);
SEXP dc_shortRowNames(SEXP arg1, SEXP arg2);
SEXP dc_copyDFattr(SEXP arg1, SEXP arg2);
SEXP dc_comment(SEXP arg1);
SEXP dc_formals(SEXP arg1);
SEXP dc_body(SEXP arg1);
SEXP dc_bodyCode(SEXP arg1);
SEXP dc_envir(SEXP arg1);
SEXP dc_parentenv(SEXP arg1);
SEXP dc_parentenvgets(SEXP arg1, SEXP arg2);
SEXP dc_envirName(SEXP arg1);
SEXP dc_makevector(SEXP arg1, SEXP arg2);
SEXP dc_substr(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_substrgets(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_abbrev(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_makenames(SEXP arg1, SEXP arg2);
SEXP dc_strtrim(SEXP arg1, SEXP arg2);
SEXP dc_typeof(SEXP arg1);
SEXP dc_commandArgs();
SEXP dc_complex(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_polyroot(SEXP arg1);
SEXP dc_fifo(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_pipe(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_stdin();
SEXP dc_stdout();
SEXP dc_stderr();
SEXP dc_isatty(SEXP arg1);
SEXP dc_rawconnection(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_rawconvalue(SEXP arg1);
SEXP dc_textconnection(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4, SEXP arg5);
SEXP dc_textconvalue(SEXP arg1);
SEXP dc_unz(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_open(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_isopen(SEXP arg1, SEXP arg2);
SEXP dc_isincomplete(SEXP arg1);
SEXP dc_isseekable(SEXP arg1);
SEXP dc_seek(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_truncate(SEXP arg1);
SEXP dc_flush(SEXP arg1);
SEXP dc_writelines(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_writebin(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4, SEXP arg5);
SEXP dc_readchar(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_writechar(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4, SEXP arg5);
SEXP dc_pushback(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_pushbacklength(SEXP arg1);
SEXP dc_clearpushback(SEXP arg1);
SEXP dc_sink(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_sinknumber(SEXP arg1);
SEXP dc_getallconnections();
SEXP dc_getconnection(SEXP arg1);
SEXP dc_sumconnection(SEXP arg1);
SEXP dc_gzcon(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_sockselect(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_memCompress(SEXP arg1, SEXP arg2);
SEXP dc_memDecompress(SEXP arg1, SEXP arg2);
SEXP dc_restart(SEXP arg1);
SEXP dc_parentframe(SEXP arg1);
SEXP dc_asPOSIXlt(SEXP arg1, SEXP arg2);
SEXP dc_asPOSIXct(SEXP arg1, SEXP arg2);
SEXP dc_formatPOSIXlt(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_strptime(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_D2POSIXlt(SEXP arg1);
SEXP dc_POSIXlt2D(SEXP arg1);
SEXP dc_dput(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_assign(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_list2env(SEXP arg1, SEXP arg2);
SEXP dc_globalenv();
SEXP dc_baseenv();
SEXP dc_emptyenv();
SEXP dc_detach(SEXP arg1);
SEXP dc_search();
SEXP dc_ls(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_env2list(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_builtins(SEXP arg1);
SEXP dc_lockEnv(SEXP arg1, SEXP arg2);
SEXP dc_envIsLocked(SEXP arg1);
SEXP dc_bndIsLocked(SEXP arg1, SEXP arg2);
SEXP dc_mkActiveBnd(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_bndIsActive(SEXP arg1, SEXP arg2);
SEXP dc_mkUnbound(SEXP arg1);
SEXP dc_isNSEnv(SEXP arg1);
SEXP dc_getNSRegistry();
SEXP dc_envprofile(SEXP arg1);
SEXP dc_geterrmessage();
SEXP dc_traceback(SEXP arg1);
SEXP dc_resetCondHands(SEXP arg1);
SEXP dc_signalCondition(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_dfltWarn(SEXP arg1, SEXP arg2);
SEXP NORET dc_dfltStop(SEXP arg1, SEXP arg2);
SEXP dc_getRestart(SEXP arg1);
SEXP dc_addRestart(SEXP arg1);
SEXP NORET dc_invokeRestart(SEXP arg1, SEXP arg2);
SEXP dc_seterrmessage(SEXP arg1);
SEXP dc_printDeferredWarnings();
SEXP dc_enablejit(SEXP arg1);
SEXP dc_compilepkgs(SEXP arg1);
SEXP dc_paren(SEXP arg1);
SEXP dc_mkcode(SEXP arg1, SEXP arg2);
SEXP dc_bcversion();
SEXP dc_growconst(SEXP arg1);
SEXP dc_putconst(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_getconst(SEXP arg1, SEXP arg2);
SEXP dc_bcprofcounts();
SEXP dc_bcprofstart();
SEXP dc_bcprofstop();
SEXP dc_setnumthreads(SEXP arg1);
SEXP dc_setmaxnumthreads(SEXP arg1);
SEXP dc_returnValue(SEXP arg1);
SEXP dc_pcre_config();
SEXP dc_address(SEXP arg1);
SEXP dc_regFinaliz(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_gctorture(SEXP arg1);
SEXP dc_gctorture2(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_gcinfo(SEXP arg1);
SEXP dc_gc(SEXP arg1, SEXP arg2);
SEXP dc_memlimits(SEXP arg1, SEXP arg2);
SEXP dc_memoryprofile();
SEXP dc_inherits(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_setS4Object(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_getOption(SEXP arg1);
SEXP dc_formatinfo(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_date();
SEXP dc_fileappend(SEXP arg1, SEXP arg2);
SEXP dc_filecreate(SEXP arg1, SEXP arg2);
SEXP dc_fileremove(SEXP arg1);
SEXP dc_filesymlink(SEXP arg1, SEXP arg2);
SEXP dc_filelink(SEXP arg1, SEXP arg2);
SEXP dc_filerename(SEXP arg1, SEXP arg2);
SEXP dc_fileinfo(SEXP arg1, SEXP arg2);
SEXP dc_direxists(SEXP arg1);
SEXP dc_Rhome();
SEXP dc_fileexists(SEXP arg1);
SEXP dc_filechoose(SEXP arg1);
SEXP dc_fileaccess(SEXP arg1, SEXP arg2);
SEXP dc_unlink(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_getlocale(SEXP arg1);
SEXP dc_setlocale(SEXP arg1, SEXP arg2);
SEXP dc_localeconv();
SEXP dc_pathexpand(SEXP arg1);
SEXP dc_capabilitiesX11();
SEXP dc_capabilities();
SEXP dc_sysgetpid();
SEXP dc_dircreate(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_l10n_info();
SEXP dc_syschmod(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_sysumask(SEXP arg1);
SEXP dc_readlink(SEXP arg1);
SEXP dc_Cstack_info();
SEXP dc_setFileTime(SEXP arg1, SEXP arg2);
SEXP dc_eSoftVersion();
SEXP dc_qsort(SEXP arg1, SEXP arg2);
SEXP dc_charToRaw(SEXP arg1);
SEXP dc_rawToChar(SEXP arg1, SEXP arg2);
SEXP dc_rawShift(SEXP arg1, SEXP arg2);
SEXP dc_rawToBits(SEXP arg1);
SEXP dc_intToBits(SEXP arg1);
SEXP dc_packBits(SEXP arg1, SEXP arg2);
SEXP dc_utf8ToInt(SEXP arg1);
SEXP dc_intToUtf8(SEXP arg1, SEXP arg2);
SEXP dc_getSymbolInfo(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_getDllTable();
SEXP dc_getRegisteredRoutines(SEXP arg1);
SEXP dc_RNGkind (SEXP arg1, SEXP arg2);
SEXP dc_setseed (SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_load(SEXP arg1, SEXP arg2);
SEXP dc_loadFromConn2(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_readln(SEXP arg1);
SEXP dc_rep_int(SEXP arg1, SEXP arg2);
SEXP dc_rep_len(SEXP arg1, SEXP arg2);
SEXP dc_unserializeFromConn(SEXP arg1, SEXP arg2);
SEXP dc_lazyLoadDBflush(SEXP arg1);
SEXP dc_getVarsFromFrame(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_sort(SEXP arg1, SEXP arg2);
SEXP dc_radixsort(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_split(SEXP arg1, SEXP arg2);
SEXP dc_which(SEXP arg1);
SEXP dc_interactive();
SEXP dc_tempdir();
SEXP dc_getenv(SEXP arg1, SEXP arg2);
SEXP dc_setenv(SEXP arg1, SEXP arg2);
SEXP dc_unsetenv(SEXP arg1);
SEXP dc_proctime();
SEXP dc_setTimeLimit(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_setSessionTimeLimit(SEXP arg1, SEXP arg2);
SEXP dc_glob(SEXP arg1, SEXP arg2);
SEXP dc_systime();
SEXP dc_pmatch(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_charmatch(SEXP arg1, SEXP arg2, SEXP arg3);
SEXP dc_makeunique(SEXP arg1, SEXP arg2);
SEXP dc_sample2(SEXP arg1, SEXP arg2);
SEXP dc_merge(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4);
SEXP dc_getwd();
SEXP dc_basename(SEXP arg1);
SEXP dc_dirname(SEXP arg1);
SEXP dc_encodeString(SEXP arg1, SEXP arg2, SEXP arg3, SEXP arg4, SEXP arg5);
SEXP dc_encoding(SEXP arg1);
SEXP dc_setencoding(SEXP arg1, SEXP arg2);
SEXP dc_validUTF8(SEXP arg1);
SEXP dc_validEnc(SEXP arg1);
SEXP dc_ICUget(SEXP arg1);
SEXP dc_crc64(SEXP arg1);
SEXP dc_tabulate(SEXP arg1, SEXP arg2);
SEXP dc_version();

#endif /* not R_INTERNAL_H */
